# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: event-calendar 2.5.1 ruby lib

Gem::Specification.new do |s|
  s.name = "event-calendar"
  s.version = "2.5.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Jeff Schuil"]
  s.date = "2014-07-22"
  s.description = "Rails helper for showing multiple, overlapping events across calendar days and rows."
  s.email = ""
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "CHANGELOG.rdoc",
    "Gemfile",
    "Gemfile.lock",
    "MIT-LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "event-calendar.gemspec",
    "generators/event_calendar/USAGE",
    "generators/event_calendar/event_calendar_generator.rb",
    "generators/event_calendar/lib/insert_routes.rb",
    "generators/event_calendar/templates/controller.rb.erb",
    "generators/event_calendar/templates/helper.rb.erb",
    "generators/event_calendar/templates/javascript.js",
    "generators/event_calendar/templates/jq_javascript.js",
    "generators/event_calendar/templates/migration.rb.erb",
    "generators/event_calendar/templates/model.rb.erb",
    "generators/event_calendar/templates/mt_javascript.js",
    "generators/event_calendar/templates/stylesheet.css",
    "generators/event_calendar/templates/view.html.erb",
    "init.rb",
    "install.rb",
    "lib/event_calendar.rb",
    "lib/event_calendar/calendar_helper.rb",
    "lib/event_calendar/orm/mongoid.rb",
    "lib/event_calendar/railtie.rb",
    "lib/generators/event_calendar/USAGE",
    "lib/generators/event_calendar/event_calendar_generator.rb",
    "lib/generators/event_calendar/templates/controller.rb.erb",
    "lib/generators/event_calendar/templates/helper.rb.erb",
    "lib/generators/event_calendar/templates/javascript.js",
    "lib/generators/event_calendar/templates/jq_javascript.js",
    "lib/generators/event_calendar/templates/migration.rb.erb",
    "lib/generators/event_calendar/templates/model.rb.erb",
    "lib/generators/event_calendar/templates/mt_javascript.js",
    "lib/generators/event_calendar/templates/stylesheet.css",
    "lib/generators/event_calendar/templates/view.html.erb",
    "lib/tasks/event_calendar_tasks.rake",
    "spec/event_calendar_spec.rb",
    "spec/fixtures/models.rb",
    "spec/spec.opts",
    "spec/spec_helper.rb",
    "uninstall.rb"
  ]
  s.homepage = "http://github.com/elevation/event_calendar"
  s.rubygems_version = "2.2.2"
  s.summary = "Rails helper for showing multiple, overlapping events across calendar days and rows."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<byebug>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.0"])
    else
      s.add_dependency(%q<byebug>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.0"])
    end
  else
    s.add_dependency(%q<byebug>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.0"])
  end
end

